spring.application.name=servicio-cursos
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/cursos_db}
spring.datasource.username=${DB_USERNAME:cursos_app}
spring.datasource.password=${DB_PASSWORD:cursos_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs

app.security.jwt.secret=${JWT_SECRET:clave-local-de-desarrollo-cambiar-32-caracteres-minimo}
app.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
