spring.application.name=servicio-matriculas
server.port=${SERVER_PORT:8083}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/matriculas_db}
spring.datasource.username=${DB_USERNAME:matriculas_app}
spring.datasource.password=${DB_PASSWORD:matriculas_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true

app.services.usuarios-url=${USUARIOS_SERVICE_URL:http://localhost:8081}
app.services.cursos-url=${CURSOS_SERVICE_URL:http://localhost:8082}
app.security.jwt.secret=${JWT_SECRET:clave-local-de-desarrollo-cambiar-32-caracteres-minimo}
app.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
