'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ClipboardPen, Pencil, RefreshCw } from 'lucide-react';
import { DashboardError, DashboardSkeleton, EmptyState, PageHeading, StatusBadge } from '@/components/dashboard-ui';
import { ActionIcon, Feedback, FormActions, Modal, ModuleToolbar } from '@/components/module-ui';
import { API, apiFetch, PageResponse } from '@/lib/api';
import { Calificacion, Curso, Estudiante, Evaluacion, Matricula, Seccion } from '@/lib/types';

const transitions: Record<string, string[]> = { BORRADOR: ['PUBLICADA', 'ANULADA'], PUBLICADA: ['CERRADA', 'ANULADA'] };

export default function EvaluacionesDocentePage() {
  const [sections, setSections] = useState<Seccion[]>([]); const [evaluations, setEvaluations] = useState<Evaluacion[]>([]); const [students, setStudents] = useState<Estudiante[]>([]); const [courses, setCourses] = useState<Record<number, Curso>>({});
  const [selectedSection, setSelectedSection] = useState<number | ''>(''); const [selectedEvaluation, setSelectedEvaluation] = useState<Evaluacion | null>(null); const [roster, setRoster] = useState<Matricula[]>([]); const [grades, setGrades] = useState<Calificacion[]>([]); const [gradeValues, setGradeValues] = useState<Record<number, string>>({});
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [createOpen, setCreateOpen] = useState(false); const [editingEvaluation, setEditingEvaluation] = useState<Evaluacion | null>(null); const [gradesOpen, setGradesOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [requestId, setRequestId] = useState(0);

  const load = useCallback(() => { Promise.all([
    apiFetch<PageResponse<Seccion>>(API.matriculas, '/api/v1/secciones/mias?size=100'), apiFetch<PageResponse<Evaluacion>>(API.evaluaciones, '/api/v1/evaluaciones?size=200'), apiFetch<PageResponse<Estudiante>>(API.usuarios, '/api/v1/estudiantes?size=500'),
  ]).then(async ([sectionPage, evaluationPage, studentPage]) => {
    const ids = [...new Set(sectionPage.contenido.map((item) => item.cursoId))]; const courseValues = await Promise.all(ids.map((id) => apiFetch<Curso>(API.cursos, `/api/v1/cursos/${id}`)));
    setSections(sectionPage.contenido); setEvaluations(evaluationPage.contenido); setStudents(studentPage.contenido); setCourses(Object.fromEntries(courseValues.map((item) => [item.id, item]))); setSelectedSection((current) => current || sectionPage.contenido[0]?.id || ''); setError('');
  }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load, requestId]);

  const visible = useMemo(() => evaluations.filter((item) => (!selectedSection || item.seccionId === selectedSection) && `${item.codigo} ${item.nombre} ${item.tipo}`.toLowerCase().includes(search.toLowerCase())), [evaluations, search, selectedSection]);

  async function saveEvaluation(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setFeedback(null); const form = new FormData(event.currentTarget);
    try { await apiFetch(API.evaluaciones, editingEvaluation ? `/api/v1/evaluaciones/${editingEvaluation.id}` : '/api/v1/evaluaciones', { method: editingEvaluation ? 'PUT' : 'POST', body: JSON.stringify({ ...(!editingEvaluation ? { seccionId: Number(form.get('seccionId')) } : {}), codigo: form.get('codigo'), nombre: form.get('nombre'), tipo: form.get('tipo'), ponderacion: Number(form.get('ponderacion')), notaMaxima: Number(form.get('notaMaxima')), fecha: form.get('fecha') }) }); setCreateOpen(false); setFeedback({ type: 'success', message: `Evaluación ${editingEvaluation ? 'actualizada' : 'creada'}.` }); setEditingEvaluation(null); setLoading(true); setRequestId((value) => value + 1); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo crear la evaluación.' }); } finally { setSubmitting(false); }
  }

  async function changeState(item: Evaluacion, estado: string) {
    if (!estado) return; try { await apiFetch(API.evaluaciones, `/api/v1/evaluaciones/${item.id}/estado`, { method: 'PATCH', body: JSON.stringify({ estado }) }); setFeedback({ type: 'success', message: 'Estado de la evaluación actualizado.' }); setLoading(true); setRequestId((value) => value + 1); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo cambiar el estado.' }); }
  }

  async function openGrades(item: Evaluacion) {
    setSelectedEvaluation(item); setSubmitting(true); setFeedback(null);
    try { const [enrollmentPage, gradeList] = await Promise.all([apiFetch<PageResponse<Matricula>>(API.matriculas, `/api/v1/matriculas/seccion/${item.seccionId}?size=500`), apiFetch<Calificacion[]>(API.evaluaciones, `/api/v1/calificaciones?evaluacionId=${item.id}`)]); setRoster(enrollmentPage.contenido); setGrades(gradeList); setGradeValues(Object.fromEntries(enrollmentPage.contenido.map((enrollment) => [enrollment.id, gradeList.find((grade) => grade.matriculaId === enrollment.id)?.valor?.toString() ?? '']))); setGradesOpen(true); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo cargar el padrón.' }); } finally { setSubmitting(false); }
  }

  async function saveGrades(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selectedEvaluation) return; setSubmitting(true); setFeedback(null);
    try { const pending = roster.filter((item) => gradeValues[item.id] !== '' && gradeValues[item.id] !== undefined); await Promise.all(pending.map((enrollment) => { const existing = grades.find((grade) => grade.matriculaId === enrollment.id); return existing
      ? apiFetch(API.evaluaciones, `/api/v1/calificaciones/${existing.id}`, { method: 'PUT', body: JSON.stringify({ valor: Number(gradeValues[enrollment.id]), observacion: null }) })
      : apiFetch(API.evaluaciones, '/api/v1/calificaciones', { method: 'POST', body: JSON.stringify({ evaluacionId: selectedEvaluation.id, matriculaId: enrollment.id, valor: Number(gradeValues[enrollment.id]), observacion: null }) }); })); setGradesOpen(false); setFeedback({ type: 'success', message: `${pending.length} calificaciones guardadas.` }); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudieron guardar las notas.' }); } finally { setSubmitting(false); }
  }

  return <><PageHeading eyebrow="Docencia" title="Evaluaciones y calificaciones" description="Configura ponderaciones, publica componentes y registra las notas de tus estudiantes." />
    {feedback && <Feedback {...feedback} onClose={() => setFeedback(null)} />}{error && <DashboardError message={error} retry={() => { setLoading(true); setRequestId((value) => value + 1); }} />}
    <section className="module-card"><div className="module-filterbar"><label>Sección</label><select value={selectedSection} onChange={(event) => setSelectedSection(event.target.value ? Number(event.target.value) : '')}><option value="">Todas</option>{sections.map((item) => <option key={item.id} value={item.id}>{item.periodoCodigo} · {courses[item.cursoId]?.codigo ?? item.cursoId} · {item.codigo}</option>)}</select><span>{visible.reduce((sum, item) => sum + Number(item.ponderacion), 0)}% configurado en la vista</span></div>
      <ModuleToolbar search={search} onSearch={setSearch} actionLabel="Nueva evaluación" onAction={() => { setEditingEvaluation(null); setCreateOpen(true); }}><button className="secondary-button" onClick={() => { setLoading(true); setRequestId((value) => value + 1); }}><RefreshCw size={15} />Actualizar</button></ModuleToolbar>
      <div className="module-body">{loading ? <DashboardSkeleton /> : visible.length === 0 ? <EmptyState title="Sin evaluaciones" description="Selecciona una sección y crea su primer componente de evaluación." /> :
        <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Evaluación</th><th>Sección</th><th>Tipo</th><th>Fecha</th><th>Peso</th><th>Escala</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.codigo} · {item.nombre}</strong><small>ID {item.id}</small></td><td>{sections.find((section) => section.id === item.seccionId)?.codigo ?? item.seccionId}</td><td>{item.tipo}</td><td>{item.fecha}</td><td>{item.ponderacion}%</td><td>0–{item.notaMaxima}</td><td><StatusBadge value={item.estado} /></td><td><div className="evaluation-actions">{item.estado === 'BORRADOR' && <ActionIcon label="Editar evaluación" onClick={() => { setEditingEvaluation(item); setCreateOpen(true); }}><Pencil size={15} /></ActionIcon>}<button className="secondary-button" onClick={() => openGrades(item)} disabled={item.estado === 'CERRADA' || item.estado === 'ANULADA'}><ClipboardPen size={14} />Notas</button><select className="select-small" value="" onChange={(event) => changeState(item, event.target.value)}><option value="">Estado…</option>{(transitions[item.estado] ?? []).map((value) => <option key={value}>{value}</option>)}</select></div></td></tr>)}</tbody></table></div>}
      </div></section>
    <Modal open={createOpen} onClose={() => { setCreateOpen(false); setEditingEvaluation(null); }} title={editingEvaluation ? 'Editar evaluación' : 'Nueva evaluación'} description="La suma de ponderaciones de una sección no puede superar 100%." wide><form className="entity-form" onSubmit={saveEvaluation}><div className="form-grid">{!editingEvaluation && <div className="form-field full"><label>Sección</label><select name="seccionId" required defaultValue={selectedSection}><option value="" disabled>Selecciona</option>{sections.filter((item) => !['FINALIZADA','CANCELADA'].includes(item.estado)).map((item) => <option key={item.id} value={item.id}>{item.periodoCodigo} · {courses[item.cursoId]?.codigo} · {item.codigo}</option>)}</select></div>}<div className="form-field"><label>Código</label><input name="codigo" defaultValue={editingEvaluation?.codigo} required maxLength={20} placeholder="PARCIAL-1" /></div><div className="form-field"><label>Nombre</label><input name="nombre" defaultValue={editingEvaluation?.nombre} required maxLength={120} /></div><div className="form-field"><label>Tipo</label><select name="tipo" defaultValue={editingEvaluation?.tipo ?? 'PRACTICA'}>{['PRACTICA','TAREA','LABORATORIO','PARCIAL','FINAL','PROYECTO','PARTICIPACION','OTRO'].map((value) => <option key={value}>{value}</option>)}</select></div><div className="form-field"><label>Ponderación (%)</label><input name="ponderacion" type="number" defaultValue={editingEvaluation?.ponderacion} step="0.01" min="0.01" max="100" required /></div><div className="form-field"><label>Nota máxima</label><input name="notaMaxima" type="number" step="0.01" min="0.01" max="100" defaultValue={editingEvaluation?.notaMaxima ?? 20} required /></div><div className="form-field"><label>Fecha</label><input name="fecha" type="date" defaultValue={editingEvaluation?.fecha} required /></div></div><FormActions submitting={submitting} onCancel={() => { setCreateOpen(false); setEditingEvaluation(null); }} label={editingEvaluation ? 'Guardar cambios' : 'Crear evaluación'} /></form></Modal>
    <Modal open={gradesOpen} onClose={() => setGradesOpen(false)} title={`Calificaciones · ${selectedEvaluation?.nombre ?? ''}`} description={`Ingresa valores entre 0 y ${selectedEvaluation?.notaMaxima ?? 20}. Los espacios vacíos no se modifican.`} wide><form className="entity-form" onSubmit={saveGrades}>{roster.length === 0 ? <EmptyState title="Sin estudiantes matriculados" description="Esta sección todavía no tiene matrículas activas." /> : <div className="data-table-wrap"><table className="data-table grade-entry"><thead><tr><th>Estudiante</th><th>Código</th><th>Matrícula</th><th>Nota</th></tr></thead><tbody>{roster.map((enrollment) => { const student = students.find((item) => item.usuarioId === enrollment.estudianteId); return <tr key={enrollment.id}><td><strong>{student ? `${student.apellidos}, ${student.nombres}` : `Estudiante ${enrollment.estudianteId}`}</strong><small>{student?.correo}</small></td><td>{student?.codigo ?? '—'}</td><td>#{enrollment.id}</td><td><input aria-label={`Nota de ${student?.nombres ?? enrollment.estudianteId}`} type="number" min="0" max={selectedEvaluation?.notaMaxima} step="0.01" value={gradeValues[enrollment.id] ?? ''} onChange={(event) => setGradeValues((values) => ({ ...values, [enrollment.id]: event.target.value }))} /></td></tr>; })}</tbody></table></div>}<FormActions submitting={submitting} onCancel={() => setGradesOpen(false)} label="Guardar notas" /></form></Modal>
  </>;
}
