'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Ban, CheckCheck, Pencil, RefreshCw } from 'lucide-react';
import { DashboardError, DashboardSkeleton, EmptyState, PageHeading, StatusBadge } from '@/components/dashboard-ui';
import { ActionIcon, Feedback, FormActions, Modal, ModuleTabs, ModuleToolbar, RowActions } from '@/components/module-ui';
import { API, apiFetch, PageResponse } from '@/lib/api';
import { Aula, Curso, Docente, Estudiante, Matricula, Periodo, Seccion } from '@/lib/types';

type Tab = 'periodos' | 'secciones' | 'matriculas';
const periodTransitions: Record<string, string[]> = { PLANIFICADO: ['MATRICULA_ABIERTA', 'CANCELADO'], MATRICULA_ABIERTA: ['EN_CURSO', 'CANCELADO'], EN_CURSO: ['FINALIZADO', 'CANCELADO'] };
const sectionTransitions: Record<string, string[]> = { PLANIFICADA: ['ABIERTA', 'CANCELADA'], ABIERTA: ['CERRADA', 'EN_CURSO', 'CANCELADA'], CERRADA: ['ABIERTA', 'EN_CURSO', 'CANCELADA'], EN_CURSO: ['FINALIZADA', 'CANCELADA'] };

export default function OperacionPage() {
  const [tab, setTab] = useState<Tab>('periodos');
  const [periods, setPeriods] = useState<Periodo[]>([]); const [sections, setSections] = useState<Seccion[]>([]); const [enrollments, setEnrollments] = useState<Matricula[]>([]);
  const [courses, setCourses] = useState<Curso[]>([]); const [classrooms, setClassrooms] = useState<Aula[]>([]); const [teachers, setTeachers] = useState<Docente[]>([]); const [students, setStudents] = useState<Estudiante[]>([]);
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null); const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState<Periodo | Seccion | null>(null); const [submitting, setSubmitting] = useState(false); const [requestId, setRequestId] = useState(0);

  const load = useCallback(() => {
    Promise.all([
      apiFetch<PageResponse<Periodo>>(API.matriculas, '/api/v1/periodos?size=100'), apiFetch<PageResponse<Seccion>>(API.matriculas, '/api/v1/secciones?size=200'),
      apiFetch<PageResponse<Matricula>>(API.matriculas, '/api/v1/matriculas?size=200'), apiFetch<PageResponse<Curso>>(API.cursos, '/api/v1/cursos?size=200'),
      apiFetch<PageResponse<Aula>>(API.cursos, '/api/v1/aulas?size=100'), apiFetch<PageResponse<Docente>>(API.usuarios, '/api/v1/docentes?size=100'),
      apiFetch<PageResponse<Estudiante>>(API.usuarios, '/api/v1/estudiantes?size=200'),
    ]).then(([periodPage, sectionPage, enrollmentPage, coursePage, roomPage, teacherPage, studentPage]) => {
      setPeriods(periodPage.contenido); setSections(sectionPage.contenido); setEnrollments(enrollmentPage.contenido); setCourses(coursePage.contenido); setClassrooms(roomPage.contenido); setTeachers(teacherPage.contenido); setStudents(studentPage.contenido); setError('');
    }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false));
  }, []);
  useEffect(() => { load(); }, [load, requestId]);
  const values = { periodos: periods, secciones: sections, matriculas: enrollments }[tab];
  const filtered = useMemo(() => values.filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())), [search, values]);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setFeedback(null); const form = new FormData(event.currentTarget);
    try {
      if (tab === 'periodos') await apiFetch(API.matriculas, editing ? `/api/v1/periodos/${editing.id}` : '/api/v1/periodos', { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ codigo: form.get('codigo'), nombre: form.get('nombre'), fechaInicio: form.get('fechaInicio'), fechaFin: form.get('fechaFin'), fechaInicioMatricula: form.get('fechaInicioMatricula'), fechaFinMatricula: form.get('fechaFinMatricula') }) });
      if (tab === 'secciones') await apiFetch(API.matriculas, editing ? `/api/v1/secciones/${editing.id}` : '/api/v1/secciones', { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ periodoId: Number(form.get('periodoId')), cursoId: Number(form.get('cursoId')), aulaId: Number(form.get('aulaId')), docenteId: Number(form.get('docenteId')), codigo: form.get('codigo'), capacidad: Number(form.get('capacidad')), horarios: [{ diaSemana: form.get('diaSemana'), horaInicio: `${form.get('horaInicio')}:00`, horaFin: `${form.get('horaFin')}:00` }] }) });
      if (tab === 'matriculas') await apiFetch(API.matriculas, '/api/v1/matriculas', { method: 'POST', body: JSON.stringify({ estudianteId: Number(form.get('estudianteId')), seccionId: Number(form.get('seccionId')) }) });
      setModalOpen(false); setFeedback({ type: 'success', message: `Registro ${editing ? 'actualizado' : 'creado'} correctamente.` }); setEditing(null); setLoading(true); setRequestId((value) => value + 1);
    } catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo crear el registro.' }); }
    finally { setSubmitting(false); }
  }

  async function changeState(resource: 'periodos' | 'secciones', id: number, estado: string) {
    if (!estado) return;
    try { await apiFetch(API.matriculas, `/api/v1/${resource}/${id}/estado`, { method: 'PATCH', body: JSON.stringify({ estado }) }); setFeedback({ type: 'success', message: 'Estado actualizado.' }); setLoading(true); setRequestId((value) => value + 1); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo cambiar el estado.' }); }
  }

  async function enrollmentAction(item: Matricula, action: 'anulacion' | 'completar') {
    try { await apiFetch(API.matriculas, `/api/v1/matriculas/${item.id}/${action}`, { method: 'PATCH', body: action === 'anulacion' ? JSON.stringify({ motivo: 'Anulación administrativa desde el portal' }) : undefined }); setFeedback({ type: 'success', message: 'Matrícula actualizada.' }); setLoading(true); setRequestId((value) => value + 1); }
    catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo actualizar la matrícula.' }); }
  }

  return <>
    <PageHeading eyebrow="Administración" title="Operación académica" description="Gestiona el calendario lectivo, las secciones, vacantes e inscripciones oficiales." />
    {feedback && <Feedback {...feedback} onClose={() => setFeedback(null)} />}{error && <DashboardError message={error} retry={() => { setLoading(true); setRequestId((value) => value + 1); }} />}
    <section className="module-card"><ModuleTabs items={[{ value: 'periodos', label: 'Periodos', count: periods.length }, { value: 'secciones', label: 'Secciones', count: sections.length }, { value: 'matriculas', label: 'Matrículas', count: enrollments.length }]} active={tab} onChange={(value) => { setTab(value); setSearch(''); }} />
      <ModuleToolbar search={search} onSearch={setSearch} actionLabel={tab === 'periodos' ? 'Nuevo periodo' : tab === 'secciones' ? 'Nueva sección' : 'Nueva matrícula'} onAction={() => { setEditing(null); setModalOpen(true); }}><button className="secondary-button" onClick={() => { setLoading(true); setRequestId((value) => value + 1); }}><RefreshCw size={15} />Actualizar</button></ModuleToolbar>
      <div className="module-body">{loading ? <DashboardSkeleton /> : filtered.length === 0 ? <EmptyState title="No hay registros" description="Crea el primer elemento o cambia la búsqueda." /> : tab === 'periodos' ?
        <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Periodo</th><th>Clases</th><th>Matrícula</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{(filtered as Periodo[]).map((item) => <tr key={item.id}><td><strong>{item.codigo}</strong><small>{item.nombre}</small></td><td>{item.fechaInicio} → {item.fechaFin}</td><td>{item.fechaInicioMatricula} → {item.fechaFinMatricula}</td><td><StatusBadge value={item.estado} /></td><td><div className="evaluation-actions">{item.estado === 'PLANIFICADO' && <ActionIcon label="Editar periodo" onClick={() => { setEditing(item); setModalOpen(true); }}><Pencil size={15} /></ActionIcon>}<select className="select-small" value="" onChange={(event) => changeState('periodos', item.id, event.target.value)}><option value="">Estado…</option>{(periodTransitions[item.estado] ?? []).map((value) => <option key={value}>{value}</option>)}</select></div></td></tr>)}</tbody></table></div>
        : tab === 'secciones' ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Sección</th><th>Curso</th><th>Docente</th><th>Vacantes</th><th>Horario</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{(filtered as Seccion[]).map((item) => <tr key={item.id}><td><strong>{item.periodoCodigo} · {item.codigo}</strong><small>ID {item.id}</small></td><td>{courses.find((course) => course.id === item.cursoId)?.codigo ?? item.cursoId}</td><td>{teachers.find((teacher) => teacher.usuarioId === item.docenteId)?.apellidos ?? item.docenteId}</td><td>{item.vacantesDisponibles} / {item.capacidad}</td><td>{item.horarios.map((schedule) => `${schedule.diaSemana.slice(0, 3)} ${schedule.horaInicio.slice(0, 5)}`).join(', ')}</td><td><StatusBadge value={item.estado} /></td><td><div className="evaluation-actions">{['PLANIFICADA', 'CERRADA'].includes(item.estado) && item.matriculados === 0 && <ActionIcon label="Editar sección" onClick={() => { setEditing(item); setModalOpen(true); }}><Pencil size={15} /></ActionIcon>}<select className="select-small" value="" onChange={(event) => changeState('secciones', item.id, event.target.value)}><option value="">Estado…</option>{(sectionTransitions[item.estado] ?? []).map((value) => <option key={value}>{value}</option>)}</select></div></td></tr>)}</tbody></table></div>
        : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Matrícula</th><th>Estudiante</th><th>Curso</th><th>Periodo</th><th>Estado</th><th /></tr></thead><tbody>{(filtered as Matricula[]).map((item) => { const student = students.find((value) => value.usuarioId === item.estudianteId); return <tr key={item.id}><td><strong>#{item.id}</strong><small>Sección {item.seccionCodigo}</small></td><td>{student ? `${student.nombres} ${student.apellidos}` : item.estudianteId}</td><td>{courses.find((course) => course.id === item.cursoId)?.codigo ?? item.cursoId}</td><td>{item.periodoCodigo}</td><td><StatusBadge value={item.estado} /></td><td>{item.estado === 'ACTIVA' && <RowActions><ActionIcon label="Completar" onClick={() => enrollmentAction(item, 'completar')}><CheckCheck size={15} /></ActionIcon><ActionIcon label="Anular" danger onClick={() => enrollmentAction(item, 'anulacion')}><Ban size={15} /></ActionIcon></RowActions>}</td></tr>; })}</tbody></table></div>}
      </div></section>
    <Modal open={modalOpen} onClose={() => { setModalOpen(false); setEditing(null); }} title={tab === 'periodos' ? `${editing ? 'Editar' : 'Crear'} periodo` : tab === 'secciones' ? `${editing ? 'Editar' : 'Crear'} sección` : 'Registrar matrícula'} wide={tab === 'secciones'}>
      <form className="entity-form" onSubmit={save}><div className="form-grid">{tab === 'periodos' && <><div className="form-field"><label>Código</label><input name="codigo" defaultValue={(editing as Periodo | null)?.codigo} required placeholder="2026-II" /></div><div className="form-field"><label>Nombre</label><input name="nombre" defaultValue={(editing as Periodo | null)?.nombre} required /></div><div className="form-field"><label>Inicio de clases</label><input name="fechaInicio" type="date" defaultValue={(editing as Periodo | null)?.fechaInicio} required /></div><div className="form-field"><label>Fin de clases</label><input name="fechaFin" type="date" defaultValue={(editing as Periodo | null)?.fechaFin} required /></div><div className="form-field"><label>Inicio de matrícula</label><input name="fechaInicioMatricula" type="date" defaultValue={(editing as Periodo | null)?.fechaInicioMatricula} required /></div><div className="form-field"><label>Fin de matrícula</label><input name="fechaFinMatricula" type="date" defaultValue={(editing as Periodo | null)?.fechaFinMatricula} required /></div></>}
        {tab === 'secciones' && <><div className="form-field"><label>Periodo</label><select name="periodoId" required defaultValue={(editing as Seccion | null)?.periodoId ?? ''}><option value="" disabled>Selecciona</option>{periods.filter((item) => ['PLANIFICADO', 'MATRICULA_ABIERTA'].includes(item.estado) || item.id === (editing as Seccion | null)?.periodoId).map((item) => <option key={item.id} value={item.id}>{item.codigo}</option>)}</select></div><div className="form-field"><label>Curso</label><select name="cursoId" required defaultValue={(editing as Seccion | null)?.cursoId ?? ''}><option value="" disabled>Selecciona</option>{courses.filter((item) => item.estado === 'ACTIVO' || item.id === (editing as Seccion | null)?.cursoId).map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.nombre}</option>)}</select></div><div className="form-field"><label>Aula</label><select name="aulaId" required defaultValue={(editing as Seccion | null)?.aulaId ?? ''}><option value="" disabled>Selecciona</option>{classrooms.filter((item) => item.estado === 'DISPONIBLE' || item.id === (editing as Seccion | null)?.aulaId).map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.capacidad} lugares</option>)}</select></div><div className="form-field"><label>Docente</label><select name="docenteId" required defaultValue={(editing as Seccion | null)?.docenteId ?? ''}><option value="" disabled>Selecciona</option>{teachers.filter((item) => item.estado === 'ACTIVO' || item.usuarioId === (editing as Seccion | null)?.docenteId).map((item) => <option key={item.id} value={item.usuarioId}>{item.apellidos}, {item.nombres}</option>)}</select></div><div className="form-field"><label>Código de sección</label><input name="codigo" defaultValue={(editing as Seccion | null)?.codigo} required placeholder="A" /></div><div className="form-field"><label>Capacidad</label><input name="capacidad" type="number" defaultValue={(editing as Seccion | null)?.capacidad} min={1} max={500} required /></div><div className="form-field"><label>Día</label><select name="diaSemana" defaultValue={(editing as Seccion | null)?.horarios[0]?.diaSemana ?? 'LUNES'}>{['LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO'].map((day) => <option key={day}>{day}</option>)}</select></div><div className="form-field"><label>Hora de inicio</label><input name="horaInicio" type="time" defaultValue={(editing as Seccion | null)?.horarios[0]?.horaInicio?.slice(0, 5)} required /></div><div className="form-field"><label>Hora de fin</label><input name="horaFin" type="time" defaultValue={(editing as Seccion | null)?.horarios[0]?.horaFin?.slice(0, 5)} required /></div></>}
        {tab === 'matriculas' && <><div className="form-field"><label>Estudiante</label><select name="estudianteId" required defaultValue=""><option value="" disabled>Selecciona</option>{students.filter((item) => item.estado === 'ACTIVO').map((item) => <option key={item.id} value={item.usuarioId}>{item.codigo} · {item.apellidos}, {item.nombres}</option>)}</select></div><div className="form-field"><label>Sección abierta</label><select name="seccionId" required defaultValue=""><option value="" disabled>Selecciona</option>{sections.filter((item) => item.estado === 'ABIERTA').map((item) => <option key={item.id} value={item.id}>{item.periodoCodigo} · {courses.find((course) => course.id === item.cursoId)?.codigo} · {item.codigo}</option>)}</select></div><div className="info-strip full">Se validarán automáticamente el periodo, las vacantes, los choques de horario y los prerrequisitos aprobados.</div></>}
      </div><FormActions submitting={submitting} onCancel={() => { setModalOpen(false); setEditing(null); }} label={editing ? 'Guardar cambios' : 'Guardar'} /></form></Modal>
  </>;
}
