'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { DashboardError, DashboardSkeleton, PageHeading, StatusBadge } from '@/components/dashboard-ui';
import { Feedback } from '@/components/module-ui';
import { API, apiFetch, PageResponse } from '@/lib/api';
import { Carrera, Estudiante } from '@/lib/types';

export default function PerfilPage() {
  const [profile, setProfile] = useState<Estudiante | null>(null); const [careers, setCareers] = useState<Carrera[]>([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null); const [requestId, setRequestId] = useState(0);
  const load = useCallback(() => { Promise.all([apiFetch<Estudiante>(API.usuarios, '/api/v1/estudiantes/me'), apiFetch<PageResponse<Carrera>>(API.cursos, '/api/v1/carreras?size=100')]).then(([value, page]) => { setProfile(value); setCareers(page.contenido); setError(''); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load, requestId]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setFeedback(null); const form = new FormData(event.currentTarget); try { const updated = await apiFetch<Estudiante>(API.usuarios, '/api/v1/estudiantes/me', { method: 'PUT', body: JSON.stringify({ nombres: form.get('nombres'), apellidos: form.get('apellidos'), documentoIdentidad: form.get('documentoIdentidad'), fechaNacimiento: form.get('fechaNacimiento'), telefono: form.get('telefono') || null, direccion: form.get('direccion') || null, carreraId: form.get('carreraId') ? Number(form.get('carreraId')) : null }) }); setProfile(updated); setFeedback({ type: 'success', message: 'Perfil actualizado correctamente.' }); } catch (reason) { setFeedback({ type: 'error', message: reason instanceof Error ? reason.message : 'No se pudo actualizar el perfil.' }); } finally { setSubmitting(false); } }
  return <><PageHeading eyebrow="Estudiante" title="Mi perfil" description="Mantén actualizados tus datos personales y la carrera vinculada a tu cuenta." />
    {feedback && <Feedback {...feedback} onClose={() => setFeedback(null)} />}{error && <DashboardError message={error} retry={() => { setLoading(true); setRequestId((value) => value + 1); }} />}
    {loading ? <DashboardSkeleton /> : profile && <section className="profile-layout"><aside className="profile-summary"><span className="profile-avatar">{profile.nombres[0]}{profile.apellidos[0]}</span><h2>{profile.nombres} {profile.apellidos}</h2><p>{profile.correo}</p><StatusBadge value={profile.estado} /><dl><div><dt>Código</dt><dd>{profile.codigo}</dd></div><div><dt>Carrera</dt><dd>{careers.find((item) => item.id === profile.carreraId)?.nombre ?? 'Sin asignar'}</dd></div></dl></aside>
      <form className="profile-form" key={`${profile.id}-${profile.nombres}-${profile.apellidos}`} onSubmit={save}><div className="form-grid"><div className="form-field"><label>Nombres</label><input name="nombres" defaultValue={profile.nombres} required maxLength={100} /></div><div className="form-field"><label>Apellidos</label><input name="apellidos" defaultValue={profile.apellidos} required maxLength={100} /></div><div className="form-field"><label>Documento de identidad</label><input name="documentoIdentidad" defaultValue={profile.documentoIdentidad} required minLength={6} maxLength={20} /></div><div className="form-field"><label>Fecha de nacimiento</label><input name="fechaNacimiento" type="date" defaultValue={profile.fechaNacimiento} required /></div><div className="form-field"><label>Teléfono</label><input name="telefono" defaultValue={profile.telefono ?? ''} /></div><div className="form-field"><label>Carrera</label><select name="carreraId" defaultValue={profile.carreraId ?? ''}><option value="">Sin asignar</option>{careers.filter((item) => item.estado === 'ACTIVO').map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.nombre}</option>)}</select></div><div className="form-field full"><label>Dirección</label><textarea name="direccion" defaultValue={profile.direccion ?? ''} maxLength={200} /></div></div><div className="form-actions"><button className="primary-small" disabled={submitting}><Save size={15} />{submitting ? 'Guardando…' : 'Guardar cambios'}</button></div></form>
    </section>}</>;
}
